### PR TITLE
Fix del entries printing

### PR DESCRIPTION
**Pull request by JuhoPaananen**
This fix utilises tabulate_entries to print when deleting entries. Added indexin to tabulate so that functionality doesn't change from previous version. Commits are quite descriptive.

### CODE REVIEW

**Review by sevonj — CHANGES_REQUESTED** [review]
image

This adds a meaningless ID column to the LIST command.

**Comment by JuhoPaananen** [comment]
It does add an ID column, as it is used to easily identify and pick entries to delete without the need to use longer "strings" for spesification. Without an ID column, delete_entries must be changed accordingly. Taking this into account, are the changes to code required?

**Comment by sevonj** [comment]
Instead of calling another function, the code could be copied into the original UI function itself.
The same does actually apply to list command too.

**Comment by JuhoPaananen** [comment]
Unfortunately I don't get what you mean; copy-paste the same code in multiple functions or what? In any case, I don't have time left (5/6h used) to redo this.

**Comment by JuhoPaananen** [comment]
If you mean app.tabulate_entries should be refractored so that it is for example in UI get_entries function, that sure can be done and is indeed a good idea. I would still leave that fix out of this.

**Comment by sevonj** [comment]
Sorry I took a while, but yes, that was my thought.

So ok, let's merge this. I'll try to refactor the thing and fix this regression if I have some spare time left at the end of this sprint.

**Review by sevonj — APPROVED** [review]

**Review by modaralgayal — APPROVED** [review]

**Pull request merged**
