### PR TITLE
Add Save and Load

### PR DESCRIPTION
**Pull request by Deeroil**
Can someone please check the conflicts, I unfortunately can't do it / don't have enough time :''))

### CODE REVIEW

**Review by sevonj — APPROVED** [review]

**Review by sevonj — CHANGES_REQUESTED** [review]
I'll see what the tests do

**Review by sevonj — APPROVED** [review]
C O N F L I C T
R E S O L V E D

**Review by tomjtoth — APPROVED** [review]
only merged commit to main was the license, skipping merging main to this branch

**Comment by tomjtoth** [comment]
oh nvmd, GitHub wouldn't let merging this without updating the branch (`main` -> `save-load`)

**Pull request merged**
