### PR TITLE
Entry editing

### PR DESCRIPTION
**Pull request by modaralgayal**

### CODE REVIEW

**Review by JuhoPaananen — APPROVED** [review]
Good job!

**Comment by sevonj** [comment]
This allows setting empty author and title.

**Comment by modaralgayal** [comment]
Thanks for the comment, i wasn't sure what checks to add. Now title and author must always contain something.

**Comment by sevonj** [comment]
@modaralgayal  Ok, so I made a fast attempt at resolving what I have mentioned in these pull requests

https://github.com/sevonj/miniprojekti/commit/9a0c5796160c97721d2e223ac653753d2cfebf75

It loops and has input checking.

**Review by tomjtoth — APPROVED** [review]
fixed it up, good to merge

**Pull request merged**
