### PR TITLE
Unique titles branch

### PR DESCRIPTION
**Pull request by modaralgayal**

### CODE REVIEW

**Review by sevonj — CHANGES_REQUESTED** [review]
We're not going to merge code that doesn't pass CI.

I'll look at the code in more detail later.

**Comment by modaralgayal** [comment]
Yeah I need some help with the failed tests

**Comment by tomjtoth** [comment]
I'm checking this now

**Review by tomjtoth — APPROVED** [review]
fixed the tests, only touched the implemented logic to pass pylint

**Review by sevonj — CHANGES_REQUESTED** [review]
The output says `Entry successfully saved to the database.`, even though the entry is not added.

As a side note, _"saved"_ might not be best wording for this.

```
Enter command (type HELP for help):
> add
Enter article citation details:
Author: aa
Title: title
Journal: aa
Year: aa
Volume: aa
Number: aa
Pages: aa
Entry successfully saved to the database.
Enter command (type HELP for help):
> list
  ID  Citekey                               Author    Title    Journal    Year
----  ------------------------------------  --------  -------  ---------  ------
   0  9ef4f777-bdd7-4f7d-8a5b-f5794ab1570f  aa        title    aa         aa
Successfully retrieved entries
Enter command (type HELP for help):
> add
Enter article citation details:
Author: bb
Title: title
Journal: bb
Year: bb
Volume: bb
Number: bb
Pages: bb
Entry successfully saved to the database.
Enter command (type HELP for help):
> list
  ID  Citekey                               Author    Title    Journal    Year
----  ------------------------------------  --------  -------  ---------  ------
   0  9ef4f777-bdd7-4f7d-8a5b-f5794ab1570f  aa        title    aa         aa
Successfully retrieved entries
Enter command (type HELP for help):
> 
```

**Comment by sevonj** [comment]
I'll take the job of fixing it

**Review by sevonj — APPROVED** [review]
Should be OK now

**Pull request merged**
