### PR TITLE
Generate automatic citekeys

### PR DESCRIPTION
**Pull request by JuhoPaananen**
Citekey generator.

Citekey format: {lastname of the first author + year in YYYY format + a-z if multiple articles with the same author and year},  for example Mäkinen2023 and if another article from Mikko Mäkinen from the year 2023 the another article gets citekey Mäkinen2023a and so on.

Applied when adding entry manually or using doi search. Does not change citekeys when .bib is loaded.

### CODE REVIEW

**Review by sevonj — APPROVED** [review]

**Review by Deeroil — APPROVED** [review]
Good job! When adding the same DOI twice it deletes the earlier one and generates a new citekey (Auto2018 => Auto2018a) but... I'll merge now :DDD

**Comment by sevonj** [comment]
The author name part could actually could be shortened to 5 letters.
Oh, and how are they capitalized? Citekey strings could be passed through lower() if they're not.

Good to start thinking these after approving.

**Comment by sevonj** [comment]
Oh, and how are they capitalized?

**Comment by sevonj** [comment]
> Oh, and how are they capitalized?

Citekey strings could be passed through lower() if they're not

**Comment by sevonj** [comment]
Good to start thinking these _after_ approving.

**Comment by JuhoPaananen** [comment]
> The author name part could actually could be shortened to 5 letters. Oh, and how are they capitalized? Citekey strings could be passed through lower() if they're not.
> 
> Good to start thinking these after approving.

I followed BibTex documentation for citekey formatting and LastnameYYYY was the first option. We can change it to all lower if preferred. Name shortening can be done as well, but not explicitly required by the customer so I would leave it later.

**Comment by JuhoPaananen** [comment]
Last commit fixes crash issues when an empty entry is added.

**Comment by sevonj** [comment]
The format isn't too crucial. I hope we don't get any issues related to case sensitivity, though.
I'm OK with the PR.

**Pull request merged**
